store/blog/urls.py
from django.urls import path
from . import views


app_name='blog'



urlpatterns = [
    path('', views.blogView, name='blog_list'),
    path('<int:id>/detail/', views.blogDetail, name='blog_detail'),
    path('add-blog/', views.addBlog, name="add_blog")
]

store/bookstore_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('contact/', include('contact.urls')),
    path('order/',include('order.urls')),
    path('blog/', include('blog.urls')),
    path('vouchers/',include('vouchers.urls',namespace='vouchers')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/dashboard/urls.py
from django.urls import path
from .views import *
from shop.views import managerCreateView

app_name = 'dashboard'

urlpatterns = [
    path('', manager_dashboard, name='manager_dashboard'),
    path('new/', managerCreateView, name='book_new'),
    path('all_orders/', orders_list, name='all_orders'),
    path('users/', userListView, name='user_list'), 
    path('voucher_list/', voucherListView, name='voucher_list'),
    path('voucher_add/', voucherCreateView, name='voucher_add'),
    path('voucher_edit/<int:voucher_id>/', voucherEditView, name='voucher_edit'),
    path('voucher_delete/<int:voucher_id>/', voucherDeleteView, name='voucher_delete')
]

store/order/urls.py
from django.urls import path
from . import views
from .views import RequestRefundView

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', views.orderHistory, name='order_history'),
    path('<int:order_id>/', views.viewOrder, name='order_detail'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

store/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns = [
        path('',views.searchResult,name='searchResult'),
        path('managerSearchResult/',views.searchResultManager ,name='managerSearchResult')
]

store/shop/urls.py
from django.urls import path
from . import views


app_name='shop'


urlpatterns = [
    path('', views.allBookCat, name='allBookCat'),
    path('books/<slug:category_slug>/', views.allBookCat, name='books_by_category'),
    path('books/<slug:category_slug>/<slug:book_slug>/', views.book_detail, name='book_detail'),
    path('new/', views.managerCreateView, name='book_new'),
    path('booksManagerList/', views.bookListView, name='book_list'),
    path('books/<slug:category_slug>/<slug:book_slug>/edit/', views.bookUpdateView, name='book_edit'),
    path('books/<slug:category_slug>/<slug:book_slug>/delete/',views.bookDeleteView, name='book_delete'),
    path('books/<slug:category_slug>/<slug:book_slug>/add', views.add_to_wishList, name='add_wishlist'),
    path('wishlists/',views.viewWishList, name='wishList_books'),
    path('books/<slug:book_slug>/delete', views.delete_from_wishList, name='wishList_delete'),
    path('top_rated/', views.topRatedBooks, name='topRatedBooks'),
    path('best_value/', views.cheapBooks, name='cheapBooks'),
    path('books/<slug:category_slug>/<slug:book_slug>/add_review/', views.addReview, name="add_review"),
    path('reviews/',views.reviewList, name="reviewList"),

    

]

store/dashboard/models.py
from django.db import models

# Create your models here.

store/dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse
from vouchers.models import Voucher
from order.models import Order, OrderItem
from shop.models import Book
from accounts.models import CustomUser
from accounts.forms import UserChangeForm
from django.db.models import Sum, DecimalField, Count, IntegerField
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models.functions import Cast
from shop.views import group_check
from datetime import datetime
from django.http import HttpResponseRedirect
from vouchers.forms import VoucherForm
from django.urls import reverse






@user_passes_test(group_check)
def manager_dashboard(request):
    vouchers = Voucher.objects.all()
    vouchers_count = vouchers.count()
    
    orders = Order.objects.all()
    books = Book.objects.all()
    books_count = books.count()
    orders_count = orders.count()
    users_count = CustomUser.objects.count()
    total_sales = Order.objects.aggregate(my_sum=Cast(Sum('total'), IntegerField()))
    this_month = datetime.now().month
    today = datetime.now().day
    this_month_sales = Order.objects.filter(created__month=this_month).aggregate(my_sum=Cast(Sum('total'), IntegerField()))
    todays_sales = Order.objects.filter(created__day=today).aggregate(my_sum=Cast(Sum('total'), IntegerField()))
    jan_sales = Order.objects.filter(created__lt='2021-01-31').filter(created__gt='2021-01-01').count()
    feb_sales = Order.objects.filter(created__lt='2021-02-28').filter(created__gt='2021-02-01').count()
    march_sales = Order.objects.filter(created__lt='2021-03-31').filter(created__gt='2021-03-01').aggregate(my_sum=Cast(Sum('total'), DecimalField()))
    april_sales = Order.objects.filter(created__lt='2021-04-30').filter(created__gt='2021-04-01').aggregate(my_sum=Cast(Sum('total'), DecimalField()))
    may_sales = Order.objects.filter(created__lt='2021-05-31').filter(created__gt='2021-05-01').count()
    june_sales = Order.objects.filter(created__lt='2021-06-30').filter(created__gt='2021-06-01').count()
    july_sales = Order.objects.filter(created__lt='2021-07-31').filter(created__gt='2021-07-01').count()
    aug_sales = Order.objects.filter(created__lt='2021-08-31').filter(created__gt='2021-08-01').count()
    sep_sales = Order.objects.filter(created__lt='2021-09-30').filter(created__gt='2021-09-01').count()
    oct_sales = Order.objects.filter(created__lt='2021-10-31').filter(created__gt='2021-10-01').count()
    nov_sales = Order.objects.filter(created__lt='2021-11-30').filter(created__gt='2021-11-01').count()
    dec_sales = Order.objects.filter(created__lt='2021-12-31').filter(created__gt='2021-12-01').count()

    
    context = {
        "orders" : orders,
        "books" : books,
        "vouchers_count": vouchers_count,
        "books_count" : books_count,
        "orders_count" : orders_count,
        "users_count" : users_count,
        'total_sales':total_sales,
        'this_month_sales' : this_month_sales,
        'todays_sales' : todays_sales,
        "jan_sales" : jan_sales,
        "feb_sales" : feb_sales,
        "march_sales" : march_sales,
        "april_sales" : april_sales,
        "may_sales" : may_sales,
        "june_sales" : june_sales,
        "july_sales" : july_sales,
        "aug_sales" : aug_sales,
        "sep_sales" : sep_sales,
        "oct_sales" : oct_sales,
        "nov_sales" : nov_sales,
        "dec_sales" : dec_sales,
    }
    return render(request, "dashboard/manager_dashboard.html", context)

@user_passes_test(group_check)
def orders_list(request):
    orders = Order.objects.all()
    books_count = Book.objects.count()
    orders_count = Order.objects.count()
    users_count = CustomUser.objects.count()
    vouchers = Voucher.objects.all()
    vouchers_count = vouchers.count()
    context = {
        "orders" : orders,
        'books_count' : books_count,
        'orders_count' : orders_count,
        'users_count' : users_count,
        "vouchers_count": vouchers_count,
        }
    return render(request, "dashboard/order_list.html", context)

@user_passes_test(group_check)
def userListView(request):
    vouchers = Voucher.objects.all()
    vouchers_count = vouchers.count()
    users = CustomUser.objects.all()
    books_count = Book.objects.count()
    orders_count = Order.objects.count()
    users_count = CustomUser.objects.count()
    context = {
     
        'users':users,
        'books_count' : books_count,
        'orders_count' : orders_count,
        'users_count' : users_count,
         "vouchers_count": vouchers_count,
        }
    return render(request, 'dashboard/user_list.html', context)


""""""   """   """   """   """   """   """   """   """   """   """   """   """   """   """   """   """   """    """

@user_passes_test(group_check)
def voucherCreateView(request):


    books_count = Book.objects.count()
    orders_count = Order.objects.count()
    users_count = CustomUser.objects.count()
    vouchers = Voucher.objects.all()
    vouchers_count = vouchers.count()
    if request.method == 'POST':
        form = VoucherForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('dashboard:voucher_list'))

    else:
        form = VoucherForm()

    return render(request, 'dashboard/voucher_add.html', {'form':form,
   
        'books_count' : books_count,
        'orders_count' : orders_count,
        'users_count' : users_count,
         "vouchers_count": vouchers_count,
    
    
    
    
    })

@user_passes_test(group_check)
def voucherListView(request):

    
    books_count = Book.objects.count()
    orders_count = Order.objects.count()
    users_count = CustomUser.objects.count()
    vouchers = Voucher.objects.all()
    vouchers_count = vouchers.count()
    context = {
           
        'books_count' : books_count,
        'orders_count' : orders_count,
        'users_count' : users_count,
        'vouchers':vouchers,
        'vouchers_count': vouchers_count,
     
        }
    return render(request, 'dashboard/voucher_list.html', context)

@user_passes_test(group_check)
def voucherEditView(request, voucher_id):
  
    books_count = Book.objects.count()
    orders_count = Order.objects.count()
    users_count = CustomUser.objects.count()
    vouchers = Voucher.objects.all()
    vouchers_count = vouchers.count()
    voucher = Voucher.objects.get(id=voucher_id)

    form = VoucherForm(request.POST or None , instance = voucher)
    if form.is_valid():
        print(request.POST)
        form.save()
        return HttpResponseRedirect(reverse('dashboard:voucher_list'))

    return render(request, 'dashboard/voucher_edit.html', {'form':form,
    
        "books_count" : books_count,
        "orders_count" : orders_count,
        "users_count" : users_count,
        "vouchers_count": vouchers_count,
    
    })

@user_passes_test(group_check)
def voucherDeleteView(request, voucher_id):

    books_count = Book.objects.count()
    orders_count = Order.objects.count()
    users_count = CustomUser.objects.count()
    vouchers = Voucher.objects.all()
    vouchers_count = vouchers.count()
    voucher = Voucher.objects.get(id=voucher_id)
    
    if request.method =="POST":
        voucher.delete()
        return HttpResponseRedirect(reverse('dashboard:voucher_list'))

    return render(request, 'dashboard/voucher_delete.html', {'voucher':voucher,
    
        "books_count" : books_count,
        "orders_count" : orders_count,
        "users_count" : users_count,
        "vouchers_count": vouchers_count,
    
    })

store/dashboard/templates/dashboard/manager_dashboard.html
{% include "dashboard/manager_navigation.html" %}

<div class="col-12 mb-5 ">
    <div class="card shadow">
        <div class="card-header text-center text-light bg-dark">
            search
        </div>
    
            <form style="" class="card-body " action="{% url 'search_app:managerSearchResult' %}" method="get">
                {% csrf_token %}
                <input  id="searcher"  class="form-control  rounded-0" type="search" placeholder="" aria-label="Search" name="q">
                <br>
                <button style="" class="btn btn-dark my-2 my-sm-0 text-center" type="submit">Search</button>
                
              
              </form>
        
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.1/dist/chart.min.js"></script>

<h4 style="font-size: 30px;" class="badge badge-warning">Total Sales All Time: €{% if total_sales.my_sum == Null %}0{% else %}{{ total_sales.my_sum }}{% endif %}</h4>
<br><h4 style="font-size: 30px;" class="badge badge-primary">Total Sales This Month: €{% if this_month_sales.my_sum == Null %}0{% else %}{{ this_month_sales.my_sum }}{% endif %}</h4>
<br><h4 style="font-size: 30px;" class="badge badge-success">Total Sales Today: €{% if todays_sales.my_sum == Null %}0{% else %}{{ todays_sales.my_sum }}{% endif %}</h4>

<!--Graphs-->
<div class="container">
	<div class="row my-5">
		<div class="col-md-6">
			<div class="bg-white">
				<canvas id="myChart1" width="400" height="300"></canvas>
				<script>
var ctx = document.getElementById('myChart1').getContext('2d');
var myChart1 = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: ["Jan '21 Sales", "Feb '21 Sales", "March '21 Sales", "April '21 Sales", "May '21 Sales", "June '21 Sales", "July '21 Sales", "August '21 Sales", 
        "September '21 Sales", "October '21 Sales", "November '21 Sales", "December '21 Sales",],
        datasets: [{
            label: 'Sales by month',
            data: [{{ jan_sales }}, {{ feb_sales }}, {{ march_sales.my_sum }}, {{ april_sales.my_sum }}, {{ may_sales }}, {{ june_sales }}, {{ july_sales }}, {{ aug_sales }},
            {{ sep_sales }}, {{ oct_sales }}, {{ nov_sales }}, {{ dec_sales }},],
            backgroundColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(238, 130, 238)',
                'rgba(155, 66, 32, 1)',
                'rgba(223, 56, 60, 1)',
                'rgba(172, 215, 224, 1)',
                'rgba(92, 92, 92, 1)',
                'rgba(123, 142, 55, 1)',
                'rgba(1, 1, 1, 1)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)',
                'rgba(155, 66, 32, 1)',
                'rgba(223, 56, 60, 1)',
                'rgba(172, 215, 224, 1)',
                'rgba(92, 92, 92, 1)',
                'rgba(123, 142, 55, 1)',
                'rgba(1, 1, 1, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});
</script>
			</div>
		</div>
		<div class="col-md-6">
			<div class="bg-white">
				<canvas id="myChart" width="400" height="400"></canvas>
				<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: [{% for book in books %} '{{ book.title }}', {% endfor %}],
        datasets: [{
            label: 'Stock Levels',
            data: [{% for book in books %} {{ book.stock }}, {% endfor %}],
            backgroundColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
            }
    }
});
</script>
			</div>
		</div>
	</div>
    </div>
	<!--End Graphs-->
</div>

store/dashboard/templates/dashboard/manager_navigation.html
{% load static %}

<link rel="icon" href="{% static 'images/chromelogo2.png' %}"
<meta charset="utf-8">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Baskervville&display=swap" rel="stylesheet">
<meta name="description" content="{% block metadescription %}{% endblock %}">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'css/custom.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
 

<nav class="navbar navbar-dark bg-dark">
	<a href="{% url 'shop:allBookCat' %}" class="navbar-brand nav-link ">
		Home</a>
	
	
<ul class="navbar-nav"> 
	<li class="nav-item">
<a class="nav-link text-light" href="{% url 'dashboard:manager_dashboard' %}">
		<!--<h2 class="new my-4" style="margint-left:5em;">
			<svg width="0.8em" height="0.8em" viewBox="0 0 16 16" class="bi bi-gear" fill="currentColor"
				xmlns="http://www.w3.org/2000/svg">
				<path fill-rule="evenodd" d="M8.837 1.626c-.246-.835-1.428-.835-1.674 0l-.094.319A1.873 1.873 0 0 1 4.377 3.06l-.292-.16c-.764-.415-1.6.42-1.184 1.185l.159.292a1.873 1.873 0 0 1-1.115 2.692l-.319.094c-.835.246-.835 1.428 0 1.674l.319.094a1.873 1.873 0 0 1 1.115 2.693l-.16.291c-.415.764.42 1.6 1.185 1.184l.292-.159a1.873 1.873 0 0 1 2.692 1.116l.094.318c.246.835 1.428.835 1.674 0l.094-.319a1.873 1.873 0 0 1 2.693-1.115l.291.16c.764.415 1.6-.42 1.184-1.185l-.159-.291a1.873 1.873 0 0 1 1.116-2.693l.318-.094c.835-.246.835-1.428 0-1.674l-.319-.094a1.873 1.873 0 0 1-1.115-2.692l.16-.292c.415-.764-.42-1.6-1.185-1.184l-.291.159A1.873 1.873 0 0 1 8.93 1.945l-.094-.319zm-2.633-.283c.527-1.79 3.065-1.79 3.592 0l.094.319a.873.873 0 0 0 1.255.52l.292-.16c1.64-.892 3.434.901 2.54 2.541l-.159.292a.873.873 0 0 0 .52 1.255l.319.094c1.79.527 1.79 3.065 0 3.592l-.319.094a.873.873 0 0 0-.52 1.255l.16.292c.893 1.64-.902 3.434-2.541 2.54l-.292-.159a.873.873 0 0 0-1.255.52l-.094.319c-.527 1.79-3.065 1.79-3.592 0l-.094-.319a.873.873 0 0 0-1.255-.52l-.292.16c-1.64.893-3.433-.902-2.54-2.541l.159-.292a.873.873 0 0 0-.52-1.255l-.319-.094c-1.79-.527-1.79-3.065 0-3.592l.319-.094a.873.873 0 0 0 .52-1.255l-.16-.292c-.892-1.64.902-3.433 2.541-2.54l.292.159a.873.873 0 0 0 1.255-.52l.094-.319z"/>
				<path fill-rule="evenodd" d="M8 5.754a2.246 2.246 0 1 0 0 4.492 2.246 2.246 0 0 0 0-4.492zM4.754 8a3.246 3.246 0 1 1 6.492 0 3.246 3.246 0 0 1-6.492 0z"/>
			</svg>
     
		</h2>-->
		Dashboard
	</a>
	</li>
</ul>
	

	</nav>



</nav>


	 <div class="container">
<div class="container pb-5">
<div class="row  mt-4">
	<div class="col-md-4">
		<div class="card shadow">
			<div class="card-header bg-dark text-white">
          Information
        </div>
			<div class="card-body">
				<marquee behavior="" direction="">
					<h3 style="font-size: 30px;" class="my-4 badge badge-danger">Only Managers Authorised To View This Page!</h3>
				</marquee>
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="card shadow">
			<div class="card-header bg-dark text-white">
          Statistics
        </div>
			<div class="card-body">
				<div class="row">
					<div class="col-md-4">
						<a class="text-decoration-none text-dark" href="{% url 'dashboard:user_list' %}">
							<div class="card my-card shadow text-center p-3">
								<h4>Users 
									<i class="fas fa-users"></i>
								</h4>
								<h3>{{users_count}}</h3>
							</div>
						</a>
					</div>
					<div class="col-md-4">
						<a class="text-decoration-none text-dark" href="{% url 'dashboard:voucher_list' %}">
							<div class="card my-card shadow text-center p-3">
								<h4 >Vouchers 
									<i class="fas fa-users"></i>
								</h4>
								<h3>{{vouchers_count}}</h3>
							</div>
						</a>
					</div>
					<div class="col-md-4 pb-3">
						<a class="text-decoration-none text-dark" href="{% url 'shop:book_list' %}">
							<div class="card my-card shadow text-center p-3">
								<h4>Products 
									<i class="fas fa-box"></i>
								</h4>
								<h3>{{books_count}}</h3>
							</div>
						</a>
					</div>
					<div class="col-md-4">
						<a class="text-decoration-none text-dark" href="{% url 'dashboard:all_orders' %}">
							<div class="card my-card shadow text-center p-3">
								<h4>Orders 
									<i class="fas fa-shipping-fast"></i>
								</h4>
								<h3> {{orders_count}} </h3>
							</div>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	
</div>
</div>

store/dashboard/templates/dashboard/order_list.html
{% load static %}

{% block content %}
{% include "dashboard/manager_navigation.html" %}


<h1 class="py-5">Orders</h1>
<div class="container">
	<table class="table">
		<thead>
			<tr>
				<th scope="col">#</th>
				<th scope="col">Ref code:</th>
				<th scope="col">Billing Name</th>
				<th scope="col">Email</th>
				<th scope="col">Refund req.</th>
				<th scope="col">Refund granted</th>
				<th scope="col">Shipped</th>
				<th scope="col">Total</th>
				<th scope="col">Activity</th>
			</tr>
		</thead>
		<tbody>
{% for order in orders %}

			<tr>
				<th scope="row">{{ order.id }}</th>
				<td>{{ order.ref_code }}</td>
				<td>{{ order.billingName }}</td>
				<td>{{ order.emailAddress }}</td>
				<td>{% if order.refund_requested == True %} <i class="fas fa-check-square"></i> {% else %} <i class="fas fa-times"></i> {% endif %} </td>
				<td>{% if order.refund_granted == True %} <i class="fas fa-check-square"></i> {% else %} <i class="fas fa-times"></i> {% endif %} </td>
				<td>{% if order.being_delivered == True %} <i class="fas fa-check-square"></i> {% else %} <i class="fas fa-times"></i> {% endif %} </td>
				<td>€{{ order.total }}</td>
				<td>
					<a style="font-size: 12px;" class="btn btn-sm btn-info" href="{% url 'order:order_detail' order.id %}">View</a>
				</td>
			</tr>
{% endfor %}

		</tbody>
	</table>
</div>
</div>
{% endblock %}
{% block title %}
	Order List - Bookspace.
{% endblock %}

store/dashboard/templates/dashboard/user_list.html
{% load static %}

{% block content %}
{% include "dashboard/manager_navigation.html" %}

<h1 class="py-5">Users</h1>
<table class="table">
	<thead>
		<tr>
			<th scope="col">ID</th>
			<th scope="col">Username</th>
			<th scope="col">Email</th>
			<th scope="col">Staff</th>
		</tr>
	</thead>
	<tbody>
{% for user in users %}

		<tr>
			<th scope="row">{{user.id}} </th>
			<td> {{ user.username }}</td>
			<td>{{ user.email }}</td>
			<td>{% if user.is_staff == True %} <i class="fas fa-check-square"></i> {% else %} <i class="fas fa-times"></i> {% endif %} </td>
		</tr>
{% endfor %}

	</tbody>
</table>
</div>
{% endblock %}
{% block title %}
	Users - Bookspace.
{% endblock %}

store/dashboard/templates/dashboard/voucher_add.html
{% include "dashboard/manager_navigation.html" %}
{% load crispy_forms_tags %}

{% block content %}



<div class="container">



<div class=" text-justify card-profile shadow p-3  mb-5  blueRefund" style="width: auto; cursor: pointer;">
<h1 class="text-center">Add Vocuher</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy}}
    <button class="btn btn-success" type="submit">Save</button>
</form>
</div>
</div>
{% endblock content %}

store/dashboard/templates/dashboard/voucher_delete.html
{% include "dashboard/manager_navigation.html" %}

{% load crispy_forms_tags %}
{% block content %}
  <h1 class="text-center">Delete</h1>
  <form class="text-center" action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ voucher.code }}"?</p>
    <button class="btn btn-danger ml-2" type="submit">Confirm</button>
  </form>
{% endblock content %}

store/dashboard/templates/dashboard/voucher_edit.html
{% include "dashboard/manager_navigation.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  
  <div class=" text-justify card-profile shadow p-3  mb-5  blueRefund" style="width: auto; cursor: pointer;">
  <h1 class="text-center">Edit</h1>
  <form action="" method="post">{% csrf_token %}
    {{ form|crispy}}
    <button class="btn btn-info mt-3" type="submit">Update</button>
  </form>
</div>
</div>
{% endblock content %}

store/dashboard/templates/dashboard/voucher_list.html
{% block content %}
{% include "dashboard/manager_navigation.html" %}
<div class="container">
<div class="row py-5">
<div class="col-md-4">
<a style="font-size: 20px;" class="btn btn-lg btn-info" href="{% url 'dashboard:voucher_add' %}">Add Voucher +</a>
</div>
<div class="col-md-8">
<h1 class="py-5">Vouchers</h1>
<table class="table">
<thead>
    <tr>
      <th scope="col">CODE</th>
      <th scope="col">Valid From</th>
      <th scope="col">Valid to</th>
	  <th scope="col">Currently Accouncing</th>
      <th scope="col">Active</th>
      <th scope="col">Discount</th>
    </tr>
  </thead>
    <tbody>
{% for voucher in vouchers %}
<tr>
<th scope="row"><span class="badge badge-primary">{{voucher.code}}</span></th>
<td>{{voucher.valid_from}}</td>
<td>{{ voucher.valid_to}}</td>
<td>
    {% if voucher.anounce%}
    <span class="badge badge-success py-1">On </span> 
    {% else %}
    <span class="badge badge-danger py-1 "> Off</span>
    {%endif%}
</td>
<td>
    {% if voucher.active%}
    <span class="badge badge-success  py-1">On</span> 
    {% else %}
    <span class="badge badge-danger  py-1"> Off</span>
    {%endif%}
</td>
<td>{{ voucher.discount}}%</td>
<td><a class="btn btn-primary" href="{% url 'dashboard:voucher_edit' voucher.id%}">Edit</a></td>
<td><a class="btn btn-danger" href="{% url 'dashboard:voucher_delete' voucher.id %}">Delete</a></td>





</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
</div>
</div>

{% endblock content%}