store/accounts/urls.py
from django.urls import path
from shop import views
from .views import signupView, signinView, signoutView, change_password, dashboardView, profileView

urlpatterns = [
    path('create/', signupView, name='signup'),
    path('login/', signinView, name='signin'),
    path('logout/', signoutView, name='signout'),
    path('password_change/', change_password, name='change_password'),
    path('dashboard/', dashboardView, name='dashboard_view'),
    path('profile/', profileView, name='profile_view'),
]

store/blog/urls.py
from django.urls import path
from . import views


app_name='blog'



urlpatterns = [
    path('', views.blogView, name='blog_list'),
    path('<int:id>/detail/', views.blogDetail, name='blog_detail'),
    path('add-blog/', views.addBlog, name="add_blog")
]

store/bookstore_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('contact/', include('contact.urls')),
    path('order/',include('order.urls')),
    path('blog/', include('blog.urls')),
    path('vouchers/',include('vouchers.urls',namespace='vouchers')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('add/<slug:book_slug>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<slug:book_slug>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<slug:book_slug>/', views.full_remove, name='full_remove'),
]

store/order/urls.py
from django.urls import path
from . import views
from .views import RequestRefundView

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', views.orderHistory, name='order_history'),
    path('<int:order_id>/', views.viewOrder, name='order_detail'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

store/shop/urls.py
from django.urls import path
from . import views


app_name='shop'


urlpatterns = [
    path('', views.allBookCat, name='allBookCat'),
    path('books/<slug:category_slug>/', views.allBookCat, name='books_by_category'),
    path('books/<slug:category_slug>/<slug:book_slug>/', views.book_detail, name='book_detail'),
    path('new/', views.managerCreateView, name='book_new'),
    path('booksManagerList/', views.bookListView, name='book_list'),
    path('books/<slug:category_slug>/<slug:book_slug>/edit/', views.bookUpdateView, name='book_edit'),
    path('books/<slug:category_slug>/<slug:book_slug>/delete/',views.bookDeleteView, name='book_delete'),
    path('books/<slug:category_slug>/<slug:book_slug>/add', views.add_to_wishList, name='add_wishlist'),
    path('wishlists/',views.viewWishList, name='wishList_books'),
    path('books/<slug:book_slug>/delete', views.delete_from_wishList, name='wishList_delete'),
    path('top_rated/', views.topRatedBooks, name='topRatedBooks'),
    path('best_value/', views.cheapBooks, name='cheapBooks'),
    path('books/<slug:category_slug>/<slug:book_slug>/add_review/', views.addReview, name="add_review"),
    path('reviews/',views.reviewList, name="reviewList"),

    

]

store/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings

# Create your models here.

class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)


class UserProfile(models.Model): 
    first_name = models.CharField(max_length=150, default="None", blank=True)
    last_name = models.CharField(max_length=150, default="None", blank=True)
    phone_number = models.CharField(max_length=10, default="9999999999", blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    email_address = models.CharField(max_length=100)
    profile_image = models.ImageField(upload_to='blogs', blank=False, default='accounts/user01.jpeg')
    colour = models.CharField(max_length=20, default="blue")

store/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser, UserProfile

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('age', 'email',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields


class UserProfileForm(ModelForm):

    class Meta:
        model = UserProfile
        fields = ['first_name','last_name','phone_number', 'colour', 'profile_image']
   

store/accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, UserProfileForm, CustomUserChangeForm
from shop.models import WishList, Review
from order.forms import RefundForm
from order.models import Order
from blog.forms import BlogForm
from blog.models import Blog
from .models import CustomUser, UserProfile
from django.contrib.auth.models import Group
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required


@login_required()
def profileView(request):
    rForm = RefundForm()
    pForm = PasswordChangeForm(request.user)
    blogform = BlogForm()
    blog = Blog.objects.filter(author=request.user)
    p = UserProfile.objects.get(user=request.user)
    totalW = WishList.objects.all()
    totalO = Order.objects.all()
    totalR = Review.objects.all()
    wishlist = WishList.objects.filter(user=request.user)
    orders = Order.objects.filter(emailAddress = request.user.email)
    reviews = Review.objects.filter(user=request.user)
    form = UserProfileForm(instance = p)
    form2 = CustomUserChangeForm(instance=request.user)
      

    
    if request.method == 'POST':
       print(request.POST)
       form = UserProfileForm(request.POST, request.FILES, instance = p)
       if form.is_valid():
           form.save()
           messages.success(request,'Your pofile has been updated!')
    
    context = {
        'totalR':totalR,
        'totalO':totalO,
        'totalW':totalW,
        'p':p,
        'wishlist' :wishlist,
        'reviews':reviews,
        'orders':orders,
        'form':form,
        'form2': form2,
        'blogform':blogform,
        'blog':blog,
        'pForm':pForm,
        'rForm':rForm
      

    }
    
    return render(request, 'profile.html', context)


@login_required()
def dashboardView(request):

    try:
        wishlist = WishList.objects.filter(user=request.user)
    except WishList.DoesNotExist:
        wishlist = 0
    
    try:
        orders = Order.objects.filter(emailAddress = request.user.email)
    except Order.DoesNotExist: 
        orders = 0
    
    try:
        reviews = Review.objects.filter(user=request.user)
    except Review.DoesNotExist:
        reviews = 0
    context = {
        'wishlist' :wishlist,
        'reviews':reviews,
        'orders':orders
    }

   
    return render(request, 'dashboard_profile.html', context)

def signupView(request):

    
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            print(CustomUser.objects.raw("SELECT email FROM accounts WHERE username = {}".format(username)))
            signup_user = CustomUser.objects.get(username=username)
            customer_group = Group.objects.get(name='Customer')
            customer_group.user_set.add(signup_user)
            print(signup_user)

            obj = UserProfile.objects.create(
                user = signup_user,
                email_address = form.cleaned_data.get('email')
            )
            obj.save()
            print(obj)

    else:
        form = CustomUserCreationForm()


    return render(request, 'signup.html', {'form':form})         

def signinView(request):



    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                try:
                    obj = UserProfile.objects.get(user=user, email_address = user.email)
        
                except UserProfile.DoesNotExist:
                    obj = UserProfile.objects.create(
                    user = user,
                    email_address = user.email
                    )
                    obj.save()
                    
                print("----------------------------------------------hello worled")
                return redirect('shop:allBookCat')
            else:
                print("=============================================hello worled")
                return redirect('signup')

            
    else:
        form = AuthenticationForm()

       
    return render(request, 'signin.html', {'form':form})   



def signoutView(request):
    logout(request)
    return redirect('signin')

@login_required()
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('signin')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_password.html', {
        'form': form
    })

store/accounts/templates/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
Password Change
{% endblock title %}
{% block content %}
<div class="container">
  <h1>Password change</h1>
  <p>Please enter your old password, for security's sake, and then enter your
  new password twice so we can verify you typed it in correctly.</p>

  <form method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <button type='submit' class="btn btn-primary my-3">Submit</button> 
  </form>
</div>
{% endblock content %}

store/accounts/templates/dashboard_profile.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
{% if category %}
{{ category.description|truncatewords:155 }}
{% else %}
Welcome to the Online Book Store where you can buy awesome books.
{% endif %}
{% endblock %}
{% block title %}
{% if category %}
{{ category.name }} - Bookspace.
{% else %}
Best Value - Bookspace.
{% endif %}
{% endblock %}
{% block content %}


<div class="container mb-5 pb-5">
<h1>Account Dashboard</h1>
<p style="font-weight: lighter;">Hi {{request.user}}, this is your account dashbaord</p>
    <div class="row mt-5">
        <div class="col-4">
            
           <a href="{% url 'shop:wishList_books' %}" style="width: 360px; " class="btn btn-dark   rounded-0 py-3">
            <i style="font-size: 40px;" class="fas fa-male d-block "></i>Wish List</a> 


        </div>
        <div class="col-4">
            <a href="{% url 'shop:reviewList'%}" style="width: 360px;" class="btn btn-dark    rounded-0 py-3">
                <i style="font-size: 40px;" class="fas fa-star d-block"></i>Reviews</a> 
        </div>
        <div class="col-4">
            <a href="{% url 'order:order_history' %}" style="width: 360px;;" class="btn btn-dark   rounded-0 py-3">
                <i style="font-size: 40px;" class="fas fa-truck d-block"></i>Orders</a> 
        </div>

    </div>
    <div class="row mt-3">

       
        <div class="col-4">
            <a href="{% url 'profile_view'%}" style="width: 360px;" class="btn btn-dark   rounded-0 py-3">
                <i style="font-size: 40px;" class="fas fa-key d-block"></i>View Profile</a> 
        </div>
        <div class="col-4">
            <a href="{% url 'shop:allBookCat' %}" style="width: 360px;" class="btn btn-dark   rounded-0 py-3">
                <i style="font-size: 40px;" class="fas fa-home d-block"></i>Home Page</a> 
        </div>
        <div class="col-4">
            <a href="{% url 'cart:cart_detail' %}" style="width: 360px;" class="btn btn-dark   rounded-0 py-3">
                <i style="font-size: 40px;" class="fas fa-shopping-cart d-block"></i>Cart Page</a> 
        </div>

    </div>

    
</div>

{% endblock content%}

store/accounts/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags%}
{% block metadescription %}
{% if category %}
{{ category.description|truncatewords:155 }}
{% else %}
Welcome to the Online Book Store where you can buy awesome books.
{% endif %}
{% endblock %}
{% block title %}
{% if category %}
{{ category.name }} - Bookspace.
{% else %}
Best Value - Bookspace.
{% endif %}
{% endblock %}
{% block content %}
<style>


			#former:hover {

				

			}
			.blue{
				transition: 100.1ms ease-in;
			}
			.bluePassword{
				transition: 100.1ms ease-in;
			}
			.blueRefund{
				transition: 100.1ms ease-in;
			}
			.blue:hover{

				background-color: #282d32;
				color: white;
				transform: translateY(-5px);
			}

			.bluePassword:hover{
				background-color: #282d32;
				color: white;
				transform: translateY(-5px);
			}
			.blueRefund:hover{
				background-color: #282d32;
				color: white;
				transform: translateY(-5px);
			}
	
	.menu {
		height: 30vh;
		width: 200px;
		z-index: 1;
		left: 0;
		margin-top: 55px;


		padding-top: 20px;
		background-color: #282d32;
		position: absolute;
		margin-bottom: -40px;



	}

	.card-profile {
		border-radius: 20px;
		;

	}

	.menu a {
		text-decoration: none;
		list-style-type: none;
		display: block;
		text-transform: uppercase;

	}

	.menu a:hover {
		background-color: grey;
	}
</style>

<div class="container-fluid">
	<div class="menu shadow-lg p-3 mb-5 ">
		<a style=" font-weight:20px; " href="{% url 'dashboard_view'%}" class="text-justify text-light btn rounded-0">
			<i class="fas fa-chevron-left"></i> dashboard
		</a>
		<a style=" font-weight:20px" class="text-justify text-light btn disabled rounded-0">Profile </a>
		<a style=" font-weight:20px" href="{% url 'shop:wishList_books'%}"
			class="text-justify text-light btn rounded-0 ">Wishlist</a>
		<a style=" font-weight:20px" href="{% url 'order:order_history'%}"
			class="text-justify text-light btn rounded-0 ">Orders</a>
		<a href="{% url 'shop:reviewList'%}" style="  font-weight:20px" class="text-justify  text-light btn rounded-0"
			aria-disabled="true">Reviews</a>
	</div>
	<div>
		<div class="row ">
			<div class="col-2">

			</div>
			<div class="col-8">



				<br>
				<h1 class="text-justify my_title">Profile</h1>
				<br>

			</div>
		</div>

	</div>


	<div class="row">
		<div class="col-2">

		</div>

		<div class="col-3 ">
			<div class=" text-center card-profile shadow p-3  mb-5 bg-white ">
				<img class="p-3 "
					style="position: inherit; height: auto; border-radius: 50%; width: 250px; height: 250px; object-fit: cover;"
					src="{{p.profile_image.url}}" alt="profile-iamge">
				<div class="card-body">
					<h2 class="card-title">
						{{p.user}}
					</h2>
					<p class="card-title text-secondary  ">
						{{p.email_address}}
					</p>
					<p class="mt-3 border-bottom">

					</p>

					<span>Wihslists {{wishlist|length}}</span>
					<div class="progress">

						<div class="progress-bar bg-warning progress-bar-striped progress-bar-animated"
							role="progressbar" style="width:{{wishlist|length}}%; " aria-valuenow="{{wishlist|length}}"
							aria-valuemin="0" aria-valuemax="{{totalW|length}}"></div>
					</div>
					<span>Reviews {{reviews|length}}</span>
					<div class="progress">

						<div class="progress-bar bg-primary progress-bar-striped progress-bar-animated"
							role="progressbar" style="width:{{reviews|length}}%; " aria-valuenow="{{reviews|length}}"
							aria-valuemin="0" aria-valuemax="{{totalR|length}}"></div>
					</div>
					<span>Orders {{orders|length}}</span>
					<div class="progress">

						<div class="progress-bar bg-success progress-bar-striped progress-bar-animated"
							role="progressbar" style="width:{{orders|length}}% " aria-valuenow="{{orders|length}}"
							aria-valuemin="0" aria-valuemax="{{totalO|length}}"></div>
					</div>
					<span>Blogs {{blog|length}}</span>
					<div class="progress">

						<div class="progress-bar bg-dark progress-bar-striped progress-bar-animated" role="progressbar"
							style="width:{{blog|length}}%; " aria-valuenow="{{blog|length}}" aria-valuemin="0"
							aria-valuemax="{{blog|length}}"></div>
					</div>
				</div>
			</div>
		</div>
		<style>

		</style>

		<div class="col-7">
			<div class=" text-justify card-profile shadow p-3  mb-5 bg-white " style="width: auto;">
				<form id="formG" class="form-group" style="font-weight: lighter; " method="POST" action=""
					enctype="multipart/form-data">
					{%csrf_token%}
					<p style="font-weight: lighter;">{{form | crispy}}</p>
					<input style="" class="btn btn-dark" type="submit">
				</form>
			</div>
		</div>
	</div>

	<div class="row">

		<div class="col-">

		</div>


		<div class="col-2">

		</div>

		<div class="col-4">
			<div class="bluePassword text-justify card-profile shadow p-3  mb-5  " style="width: auto; cursor: pointer;">
				<a style="cursor: pointer;" id="formPassword"
					class="text-center  bg-primary btn-primary rounded">
					<h5 id="former" class="my-2">Password Reset</h5>
				</a>
				<form id="PasswordForm" style="display:none;" class="form-group" style="font-weight: lighter; "
					method="POST" action="{% url 'change_password' %}" enctype="multipart/form-data">
					{%csrf_token%}
					<p style="font-weight: lighter;">{{pForm | crispy}}</p>
					<input class="text-center" style="background-color:rgb(9, 108, 255)" class="btn " type="submit">
				</form>
			</div>
		</div>
		<div class="col-4">
			<div class=" text-justify card-profile shadow p-3  mb-5  blueRefund" style="width: auto; cursor: pointer;">
				<a style="" id="formRefund" class="text-center bg-primary btn-primary  rounded">
					<h5 id="former" class="my-2"> Request Refund</h5>
				</a>



				<form id="RefundForm" style="display:none;" class="form-group" style="font-weight: lighter; "
					method="POST" action="{% url 'order:request-refund' %}" enctype="multipart/form-data">
					{%csrf_token%}
					<p style="font-weight: lighter;">{{rForm | crispy}}</p>
					<input class="text-center" style="background-color:rgb(9, 108, 255)" class="btn " type="submit">
				</form>
			</div>
		</div>
		<div class="col-4">


		</div>
		
		
		
		<div class="col-4">
			<div id="ç" class=" text-justify card-profile shadow p-3  mb-5  blue" style="width: auto; cursor: pointer;">
				<a style="" id="formBlog" class="text-center bg-primary btn-primary  rounded">
					<h5 id="former" class="my-2">Create Blog</h5>
				</a>



				<form id="blogForm" style="display:none;" class="form-group" style="font-weight: lighter; "
					method="POST" action="{% url 'blog:add_blog'%}" enctype="multipart/form-data">
					{%csrf_token%}
					<p style="font-weight: lighter;">{{blogform | crispy}}</p>
					<input class="text-center" style="background-color:rgb(9, 108, 255)" class="btn " type="submit">
				</form>
			</div>
		</div>
	</div>
	<script>
		blogColour = document.querySelector(".blue")
		blueColourPassword = document.querySelector(".bluePassword")
		blueColourRefund = document.querySelector(".blueRefund")		
		blogForm = document.getElementById("formBlog");
		formBlog = document.getElementById("blogForm")
		formRefund = document.getElementById("RefundForm")
		RefundForm = document.getElementById("formRefund");
		PasswordForm = document.getElementById("formPassword");
		formPassword = document.getElementById("PasswordForm")
		var flagger;
		var flaggerPassowrd;
		var flaggerRefund;
		blogForm.addEventListener("click", toggleer);
		PasswordForm.addEventListener("click", toggleerPassword);
		RefundForm .addEventListener("click", toggleerRefund);

		function toggleer() {
			if (flagger) {
				formBlog.style.display = "none";
				blogColour.classList.add("blue")
				flagger = false
			}

			else {
				formBlog.style.display = "block";
				blogColour.classList.remove("blue")
				flagger = true
			}


		}
		function toggleerPassword() {
			if (flaggerPassowrd) {
				formPassword.style.display = "none";
				blueColourPassword.classList.add("bluePassword")
				flaggerPassowrd = false
			}

			else {
				formPassword.style.display = "block";
				blueColourPassword.classList.remove("bluePassword")
				flaggerPassowrd = true

			}

		}
			function toggleerRefund() {
			if (flaggerRefund) {
				formRefund.style.display = "none";
				blueColourRefund.classList.add("blueRefund")
				flaggerRefund = false
			}

			else {
				formRefund.style.display = "block";
				blueColourRefund.classList.remove("blueRefund")
				flaggerRefund = true
			}


		
		}


	</script>




</div>


<!--
	<h1 style="font-weight: lighter;" class="mb-5">Profile - {{p.user}}</h1>
	<div class="row">
		{% if p%}

		<div class="col-4">
			<div class="text-justify">
				<img class="profile-pic "
					style=" height: auto; border-radius: 50%; width: 350px; height: 350px; object-fit: cover;"
					src="{{p.profile_image.url}}" alt="profile-iamge">

				
				<h1 style="font-size: 40px; font-family:Helvetica;" class=" pt-5 text-justify">{{p.first_name}} {{p.last_name}}</h1>
				<h1 style="font-size: 30px;" class="text-justify text-secondary">{{p.user}}</h1>
				<p>{{p.email_address}}</p>
				<p>{{p.colour}}</p>
				<p>Orders Placed {{orders|length}}</p>
				<p>Items in WishList {{wishlist|length}}</p>
				<p>Reviews By {{request.user}}: {{reviews|length}}</p>
				
			</div>
			{%endif%}
		</div>

			<div class="col-8">
				<form style="font-weight: lighter;" method="POST" action="" enctype="multipart/form-data">
					{%csrf_token%}


					<p style="font-weight: lighter;">{{form | crispy}}</p>


					<input style ="background-color:{{p.colour}}" class="btn " type="submit">
				</form>

			</div>






		
	</div>
	<div class="row">



		
	</div>-->
</div>



{% endblock content %}

store/accounts/templates/signin.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block metadescription %}
	Sign in.
{% endblock %}
{% block title %}
	Login - Bookspace.
{% endblock %}
{% block content %}
	<div class="container">
		<br>
		<h1 class="my_title text-center">Login or Create a New Account</h1>
		<br>
		<div class="row">
			<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center my_custom_div">
				<br>
				<h2 class="my_title">New Customer?</h2>
				<br>
				<a href="{% url 'signup' %}" class="btn btn-dark">Create New Account</a>
			</div>
			<div class="col-12 col-sm-12 col-md-12 col-lg-6">
				<div>
					<br>
					<h2 class="my_title">Registered Customers Only</h2>
					<form method="post">
						{% csrf_token %}
						<p>{{ form | crispy }}</p>
						<button type="submit" class="btn btn-dark">Login</button>
					</form>
					<br>
				</div>
				
			</div>
		</div>
		<br>
	</div>
	<br>
{% endblock %}

store/accounts/templates/signup.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block metadescription %}
	Sign up to get a new account with us.
{% endblock %}
{% block title %}
	Create Account - Bookspace.
{% endblock %}
{% block content %}
	<div>
		{% if not form.is_valid %}
			<div class="mx-auto">
				<br>
				<h1 class="my_title text-center">Create a new account</h1>
				<br>
				<div class="col-9 col-sm-9 col-md-6 col-lg-5 mx-auto bg-light">
					<br>
					<p>Enter the following information to create a new account.</p>
					<form method="post">
						<p>{{ form | crispy }}</p>
						{% csrf_token %}
						<button type="submit" class="btn btn-dark">Register Account</button>
					</form>
					<br>
				</div>
			</div>
		{% else %}
			<div class="mx-auto">
				<br>
				<h1 class="my_title text-center">Your account has been successfully created</h1>
				<br>
				<div>
					<p class="text-center">
						Dear Customer,
						<br>
						<br>
						Your account has been created and it is ready to use.
						<br>
                        <a href="{% url 'signin' %}">Click here to Sign in</a> and enjoy the 
                        variety of books that we have at the Book store.
					</p>
				</div>
			</div>

		{% endif %}
	</div>
	<br>
{% endblock %}