store/blog/urls.py
from django.urls import path
from . import views


app_name='blog'



urlpatterns = [
    path('', views.blogView, name='blog_list'),
    path('<int:id>/detail/', views.blogDetail, name='blog_detail'),
    path('add-blog/', views.addBlog, name="add_blog")
]

store/bookstore_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('contact/', include('contact.urls')),
    path('order/',include('order.urls')),
    path('blog/', include('blog.urls')),
    path('vouchers/',include('vouchers.urls',namespace='vouchers')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('add/<slug:book_slug>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<slug:book_slug>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<slug:book_slug>/', views.full_remove, name='full_remove'),
]

store/dashboard/urls.py
from django.urls import path
from .views import *
from shop.views import managerCreateView

app_name = 'dashboard'

urlpatterns = [
    path('', manager_dashboard, name='manager_dashboard'),
    path('new/', managerCreateView, name='book_new'),
    path('all_orders/', orders_list, name='all_orders'),
    path('users/', userListView, name='user_list'), 
    path('voucher_list/', voucherListView, name='voucher_list'),
    path('voucher_add/', voucherCreateView, name='voucher_add'),
    path('voucher_edit/<int:voucher_id>/', voucherEditView, name='voucher_edit'),
    path('voucher_delete/<int:voucher_id>/', voucherDeleteView, name='voucher_delete')
]

store/order/urls.py
from django.urls import path
from . import views
from .views import RequestRefundView

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', views.orderHistory, name='order_history'),
    path('<int:order_id>/', views.viewOrder, name='order_detail'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

store/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns = [
        path('',views.searchResult,name='searchResult'),
        path('managerSearchResult/',views.searchResultManager ,name='managerSearchResult')
]

store/shop/urls.py
from django.urls import path
from . import views


app_name='shop'


urlpatterns = [
    path('', views.allBookCat, name='allBookCat'),
    path('books/<slug:category_slug>/', views.allBookCat, name='books_by_category'),
    path('books/<slug:category_slug>/<slug:book_slug>/', views.book_detail, name='book_detail'),
    path('new/', views.managerCreateView, name='book_new'),
    path('booksManagerList/', views.bookListView, name='book_list'),
    path('books/<slug:category_slug>/<slug:book_slug>/edit/', views.bookUpdateView, name='book_edit'),
    path('books/<slug:category_slug>/<slug:book_slug>/delete/',views.bookDeleteView, name='book_delete'),
    path('books/<slug:category_slug>/<slug:book_slug>/add', views.add_to_wishList, name='add_wishlist'),
    path('wishlists/',views.viewWishList, name='wishList_books'),
    path('books/<slug:book_slug>/delete', views.delete_from_wishList, name='wishList_delete'),
    path('top_rated/', views.topRatedBooks, name='topRatedBooks'),
    path('best_value/', views.cheapBooks, name='cheapBooks'),
    path('books/<slug:category_slug>/<slug:book_slug>/add_review/', views.addReview, name="add_review"),
    path('reviews/',views.reviewList, name="reviewList"),

    

]

store/shop/forms.py
from django.forms import ModelForm
from .models import Book, Category,Review


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

class BookRatingForm(ModelForm):
    class Meta:
        model = Book
        fields = ['star_rating']


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['subject','rating', 'comment']

store/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Book, WishList, Review
from django.urls import reverse_lazy
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from .forms import BookForm, ReviewForm, BookRatingForm
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView, DetailView
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.urls import reverse
from django.contrib import messages
from order.models import Order
from accounts.models import CustomUser, UserProfile
from django.core.exceptions import ValidationError
from vouchers.models import Voucher


def group_check(user):
    if user.groups.filter(name="Manager").exists() == True:
        return True
    else:
        return False

@login_required()
def reviewList(request):
    reviews = Review.objects.filter(user = request.user)
   
    return render(request, 'shop/reviews.html', {'reviews':reviews})
    

def cheapBooks(request):
    booksCheapF = Book.objects.filter(category='b6e303f8-d681-4aa2-ab8a-ad3b27a62015')
    booksCheapFiction = booksCheapF.order_by('price')[:6]

    booksCheapC= Book.objects.filter(category='1a8c0bf6-85cf-4170-ab6b-45604dd43cf2')
    booksCheapChildren = booksCheapC.order_by('price')[:6]

    booksCheapN= Book.objects.filter(category='f1b46f0d-7ee6-4ecb-a649-aaeb6407f836')
    booksCheapNon = booksCheapN.order_by('price')[:6]

    for i in booksCheapChildren:
        print(i.price)

    for l in booksCheapFiction:
        print(l.price)
    
    for j in booksCheapNon:
        print(j.price)



    return render(request, 'shop/book_cheap.html', {'booksCheapChildren':booksCheapChildren, 'booksCheapFiction':booksCheapFiction,'booksCheapNon':booksCheapNon })


def topRatedBooks(request):

    

    booksPopulateF = Book.objects.filter(category='b6e303f8-d681-4aa2-ab8a-ad3b27a62015')
    booksRatedFiction = booksPopulateF.order_by('-star_rating')[:6]

    booksPopC= Book.objects.filter(category='1a8c0bf6-85cf-4170-ab6b-45604dd43cf2')
    booksRatedChildren = booksPopC.order_by('-star_rating')[:6]

    booksPopN= Book.objects.filter(category='f1b46f0d-7ee6-4ecb-a649-aaeb6407f836')
    booksRatedNon = booksPopN.order_by('-star_rating')[:6]

    for i in booksRatedChildren:
        print(i.star_rating)

    for l in booksRatedFiction:
        print(l.star_rating)
    
    for j in booksRatedNon:
        print(j.star_rating)



    return render(request, 'shop/book_rating.html', {'booksRatedChildren':booksRatedChildren, 'booksRatedFiction':booksRatedFiction,'booksRatedNon':booksRatedNon })

def book_detail(request, category_slug, book_slug):
  
    bookCategory = Book.objects.filter(category__slug =category_slug)
    booksInCategory = bookCategory.order_by('?')[:6]

    print(request.POST)
    form = ReviewForm()
    try:
        book = Book.objects.get(category__slug=category_slug, slug=book_slug)
    except Exception as e:
        raise e

    Booker = Book.objects.all()


    rating_form = BookRatingForm()
    ratings = Review.objects.filter(review_item__slug = book_slug)
    one = 0
    two = 0
    three = 0
    four = 0
    five = 0
    half = False
    for i in ratings:
        if i.rating == 1:
            one = one +1
        if i.rating == 2:
            two = two +1
        if i.rating == 3:
            three = three +1
        if i.rating == 4:
            four = four +1
        if i.rating == 5:
            five = five +1
    try:
        total = (5*five + 4*four + 3*three + 2*two +1*one) / (one +two+three+four+five)
    except ZeroDivisionError as e:
        total = 0

    book.star_rating = total
    book.save()
        
    rounded = round(total)
    print(total)
    print(rounded)
    if total >= 1.5 and total < 2:
        rounded = 1
        half = True
    if total >= 2.5 and total < 3:
        rounded = 2
        half = True
    if total >= 3.5 and total < 4:
        rounded = 3
        half = True
    if total >= 4.5 and total < 5:
        rounded = 4
        half = True
    if total >= 5.0:
        rounded = 5
        half = False
        print("hello")
    
    print(rounded)
    UserImage = UserProfile.objects.all()
    reviewss = Review.objects.filter(review_item__slug=book_slug)
    reviews = reviewss.order_by('-created_date')

    

    
    if half:
        greyStars = 4 - rounded
    else:
        greyStars = 5 - rounded

    print(greyStars)
    print(rounded)

    

    return render(request, 'shop/book.html', {'booksInCategory':booksInCategory, 'book':book,'UserImage':UserImage, 'half':half, 'form':form, 'reviews':reviews, 'rounded':rounded, 'greyStars':greyStars})

@login_required()
def add_to_wishList(request, book_slug, category_slug):
    print(book_slug)
    book = get_object_or_404(Book, slug=book_slug)
    

    try :
        obj = WishList.objects.get(user=request.user, wished_item=book)
        messages.warning(request, 'Item already added in wishlist ')
        
    except WishList.DoesNotExist:
        obj = WishList.objects.create(
            user = request.user, 
            wished_item=book,
        )
        obj.save()
        messages.success(request,'"' +str(obj.wished_item) +'" added to Wish List')
   
    return HttpResponseRedirect(book.get_absolute_url())

@login_required()
def delete_from_wishList(request, book_slug):
    
    book = WishList.objects.get(wished_item__slug=book_slug, user = request.user)
    book.delete()
    messages.success(request, 'Successfully deleted from Wish List')

    return HttpResponseRedirect('/wishlists/')


@login_required() 
def viewWishList(request):
    managerCheck = False
    books = WishList.objects.filter(user = request.user)
    return render(request, 'shop/wishlist_books.html', {'books':books})

def allBookCat(request, category_slug=None):
    managerCheck = False

  

    if request.user.groups.filter(name="Manager").exists() == True:
        managerCheck = True

    c_page = None
    books = None
    if category_slug != None:
        c_page = get_object_or_404(Category, slug=category_slug)
        books = Book.objects.filter(category=c_page, availible=True) 
    else:
        books = Book.objects.all().filter(availible=True)
    
    paginator = Paginator(books,24)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        books = paginator.page(page)
    except (EmptyPage,InvalidPage):
        books = paginator.page(paginator.num_pages) 

    return render(request, 'shop/category.html', {'category':c_page,'books':books,'managerCheck':managerCheck })

@user_passes_test(group_check)
def managerCreateView(request):

    vouchers_count = Voucher.objects.count()
    managerCheck = True
    books = Book.objects.all()
    books_count = Book.objects.count()
    orders_count = Order.objects.count()
    users_count = CustomUser.objects.count() 
    books = Book.objects.all().filter(availible=True)
    managerCheck = True
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('')

    else:
        form = BookForm()

    return render(request, 'shop/book_new.html', {'form':form,'managerCheck':managerCheck,
            'books_count' : books_count,
        'orders_count' : orders_count,
        'users_count' : users_count,
        'books':books,
        'managerCheck':managerCheck,
        "vouchers_count":vouchers_count
    
    })

@user_passes_test(group_check)
def bookListView(request):
    vouchers_count = Voucher.objects.count()
    managerCheck = True
    books = Book.objects.all()
    books_count = Book.objects.count()
    orders_count = Order.objects.count()
    users_count = CustomUser.objects.count() 
    context = {
        'books_count' : books_count,
        'orders_count' : orders_count,
        'users_count' : users_count,
        'books':books,
        'managerCheck':managerCheck,
        "vouchers_count":vouchers_count
        }
    return render(request, 'shop/book_list.html', context)

@user_passes_test(group_check)
def bookUpdateView(request, category_slug, book_slug):
    managerCheck = True
    managerCheck = True
    vouchers_count = Voucher.objects.count()
    orders = Order.objects.all()
    books = Book.objects.all()
    books_count = books.count()
    orders_count = orders.count()
    users_count = CustomUser.objects.count()
    book = Book.objects.get(category__slug=category_slug, slug=book_slug)

    form = BookForm(request.POST or None, request.FILES or None , instance = book)
    if form.is_valid():
        print(request.POST)
        form.save()
        return HttpResponseRedirect('/')

    return render(request, 'shop/book_edit.html', {'form':form,'managerCheck':managerCheck,
    "orders" : orders,
        "books" : books,
        "books_count" : books_count,
        "orders_count" : orders_count,
        "users_count" : users_count,
        "vouchers_count":vouchers_count
    
    })

@user_passes_test(group_check)
def bookDeleteView(request, category_slug, book_slug):
    vouchers_count = Voucher.objects.count()
    managerCheck = True
    orders = Order.objects.all()
    books = Book.objects.all()
    books_count = books.count()
    orders_count = orders.count()
    users_count = CustomUser.objects.count()
    book = Book.objects.get(category__slug=category_slug, slug=book_slug)
    
    if request.method =="POST":
        book.delete()
        return HttpResponseRedirect('/')

    return render(request, 'shop/book_delete.html', {'book':book,'managerCheck':managerCheck,
    "orders" : orders,
        "books" : books,
        "books_count" : books_count,
        "orders_count" : orders_count,
        "users_count" : users_count,
         "vouchers_count":vouchers_count
    

store/shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<link rel="icon" href="{% static 'images/chromelogo2.png' %}" <meta charset="utf-8">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Baskervville&display=swap" rel="stylesheet">
	<meta name="description" content="{% block metadescription %}{% endblock %}">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
		integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
	<title>{% block title %}{% endblock %}</title>
</head>

<body style="background-color:white">
	<style>

	</style>
	

	{%if anouncemnets %}

	{%for anouncemnet in anouncemnets%}


	<div  class=" bg-danger pt-2 pb-1" >




		<h6 style="font-weight: bolder; font-family: Helvetica;" class=" text-light text-center">Get
			<span style="text-decoration: underline;" class="bade bage-warning"> {{anouncemnet.discount}}% off</span>
			with code:
			<span class="badge badge-warning">{{anouncemnet.code}}</span>
			| Ends <span style="text-decoration: ;" class="badge badge-primary text-light">{{anouncemnet.valid_to}}
			</span>
		
		</h6>
		



	</div>
	{%endfor%}
	{%endif%}

	

	<div style="overflow-x: hidden;" class="container-fluid">
		<div class="container-fluid navbar-fixed-top my_top_navbar_div">
			{% include 'top-navbar.html' %}
		</div>
		{% include 'header.html' %}
		{% include 'navbar.html' %}

		<div class="container">

			{% if messages %}
			{% for message in messages %}
			<div class=" text-center alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
				{{ message }}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			{% endfor %}
			{% endif %}
		</div>
		{% block content %}
		{% endblock %}
		<!--<hr style="margin-bottom:150px;"></hr>-->

	</div>
	<div style=" overflow-x: hidden; margin-left: -0px; " class="">
		{% include 'footer.html' %}
	</div>

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
		integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
		integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
		crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
		integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
		crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"
		integrity="sha512-n/4gHW3atM3QqRcbCn6ewmpxcLAHGaDjpEBu4xZd47N0W2oQ+6q7oc3PXstrJYXcbNU1OHdQ1T7pAP+gi5Yu8g=="
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.1/dist/chart.min.js"></script>

</body>

</html>

store/shop/templates/footer.html
<div class="footer-dark " style="overflow-x: hidden; ">
        <footer style="margin-top: 100px; padding-bottom: 100px; ;">
            
            <div class="container">
                <div class="row">
                    <div class="col-md-6 item">
                        <h3>Bookspace.</h3>
                    </div>
                    <div class="col item social">
					<a href="https://www.facebook.com/"><i class="icon ion-social-facebook"></i></a>
					<a href="https://twitter.com/"><i class="icon ion-social-twitter"></i></a>
					<a href="https://snapchat.com/"><i class="icon ion-social-snapchat"></i></a>
					<a href="https://instagram.com/"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">Bookspace. © 2021</p>
            </div>
        </footer>
    </div>

store/shop/templates/header.html
{% load static %}
<header style="margin-top: -0px;">
    <div style="text-align: center;">
        <a href="{% url 'shop:allBookCat' %}"><img  style="width:330px;" src="{% static 'images/logoOne.png' %}" alt="Online Book Store"></a>
    </div>
   
</header>
 

store/shop/templates/navbar.html
<style>
  .nav-item>a{
    color: black;
    
  }
  .ln>a:hover{
    color: white; 

  }
  .mouse{
    padding:10px 10px;
    color: black;
    text-decoration: none;
    list-style-type: none;
    font-style: normal;

  }
.mouse:hover{
background-color: black;
color: white;


}

</style>
</div>

<nav   style=" margin-bottom: 4.9px; position: sticky; top: 0; z-index: 2; background-color: white;" class=" border-top navbar navbar-expand-lg navbar-light border-bottom">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    

    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li style="font-size: 13px; margin-left: 30px;" class="nav-item ln">
          <a style="font-size:10px;  display: inline-block; margin-right:0px;" class= "btn rounded-0 mouse" href="{% url 'shop:allBookCat'%}">All Books </a>|
          {% for cat in links %}
            <a style="font-size:10px;  display: inline-block; margin-left: -10px; " class="btn rounded-0 mouse" href="{{cat.get_absolute_url}}">{{cat.name}} </a>|
          {% endfor %}
          <a style="font-size:10px; display: inline-block; margin-left: -10px;" class="btn rounded-0 mouse" href="{%url 'shop:cheapBooks' %}">Best Value </a>|
          <a style="font-size:10px;  display: inline-block; margin-left: -10px;" class="btn rounded-0 mouse"  href="{%url 'shop:topRatedBooks' %}">Top Star Rated </a>|
        </li>
      </ul>
    </div>
      {% if item_count > 0 %}
      <form class="form-inline my-2 my-lg-0"  style="margin-right: 0px;" action="{% url 'search_app:searchResult'%}" method="get">
        {% csrf_token %}
        <input style="border: 2px solid black; width: 290px;" class="form-control mr-sm-2 rounded-0" type="search" placeholder="Title, name, ISBN or publisher" aria-label="Search" name="q">
        <!--<button class="btn btn-dark my-1 my-sm-0" type="submit">Search</button>-->
          <button style="margin-left: -40px;" class="btn btn-dark  rounded-0" type="submit"><i class="fas fa-search"></i></button>
      </form>
      
      <ul  class="navbar-nav mr-auto">
        
          <li style="margin-right: 100px;" class="nav-item">
          <a class=" text-dark nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i><span class="  badge badge-danger">{{item_count}}</span></a>
          
        </li>

      </ul>
    
        {%else %}
        <form style="margin-right: 160px;" class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult'%}" method="get">
          {% csrf_token %}
          <input  id="searcher" style="border: 2px solid black; width: 290px;" class="form-control mr-sm-2 rounded-0" type="search" placeholder="Title, name, ISBN or publisher" aria-label="Search" name="q">
          <!--<button style="" class="btn btn-dark my-2 my-sm-0" type="submit">Search</button>-->
          <button style="margin-left: -40px;" class="btn btn-dark  rounded-0" type="submit"><i class=" fas fa-search"></i></button>
        
        </form>
        
        {% endif%}
     
        
    </div>


</nav>

store/shop/templates/top-navbar.html
<style>
	ul>li>a:hover{
		text-decoration: underline;
	}
</style>

<div class="container" >
	<div class="my_custom_menu">
		
		<ul style="position: sticky; top: 0; z-index: 2; background-color: white;"  class="text-right">

			<li  class="mt-2" style="float: left; margin-right: -10px;">
				{{profile.user}} 
				<a href="{% url 'shop:allBookCat' %}">Home</a> |
			</li>

			<li  class="mt-2" style="float: left;">
				
				<a href="/contact">Contact</a> |
			</li>
			<li class="mt-2" style="float: left; margin-left: -12px; margin-right: 12px;;">
				<a href="{% url 'blog:blog_list'%}"> Blog</a> |
			</li>
		
			{% if user.is_authenticated %}
			<li  class="mt-2" style="float: left; margin-left: -21px;">
				<a href="{% url 'dashboard_view'%}">ACCOUNT</a> |
			</li>
			{% if request.user.groups.all.0.name == "Manager" %}
			<li  class="mt-2" style="float: left; margin-left: -12px; margin-right: 12px;">
				<a href="{% url 'dashboard:manager_dashboard' %}">dashboard</a> |
			</li>
			{% endif %}
			{% endif %}
			{%if request.user.groups.all.0.name == "Manager" %}
		
				<span class="badge badge-dark">Manager</span>
			
			{%endif%}

			{% if user.is_authenticated %}
			<li class="dropdown">
                <!--Welcome,--> 
				<a style="height: 0px;" href="{% url 'profile_view'%}" class="" 
                aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
			{%for i in profile%}<img style="position: inherit; height: auto; border-radius: 50%; width: 25px; height: 25px; object-fit: cover;"
				src="{{i.profile_image.url}}">{%endfor%}
				<div class="dropdown-menu dropdown-menu-right"> 
			<!--	<a  href="{% url 'order:order_history' %}" class="dropdown-item">Order History</a>
					<a  href="{% url 'order:request-refund' %}" class="dropdown-item">Request Refund</a>-->	
		
			{% if managerCheck %}
			<a class="dropdown-item" href="{% url 'shop:book_new' %}">+add Book</a>
			<a  class="dropdown-item" href="{% url 'shop:book_list' %}">+list Book</a>
				{% endif %}
				</div>
			</li>
			<span style="margin-left: -14px; margin-right: 5px;">|</span>
		
			<li>
				<a href="{% url 'signout' %}">Sign Out</a> |
			</li>
			<li  style="display: inline-block; margin-right: -170px; margin-left: -18px; padding-right: 120px;" class="nav-item">
				
				<a class="nav-link" href="{% url 'shop:wishList_books' %}"> <i style="margin-left: -15px; margin-right: 5px; "class="fas fa-heart"></i>Wish List</a>
			</li>
			{% else %}
			<li style="display: inline-block; margin-right: -20px;">
				<i class="fas fa-user-plus"></i>
				<a href="{% url 'signup' %}">Sign Up </a>
			</li>
			/
			
			<li style="display: inline-block; margin-right: -25px;">
				<a href="{% url 'signin' %}"> Sign In </a>
			</li>
			<span style="margin-left: 10px; margin-right: 10px;" id="divider">|</span>
			
			<li  style="display: inline-block; margin-right: -170px; margin-left: -18px; padding-right: 120px;" class="nav-item">
				
				<a class="nav-link" href="{% url 'shop:wishList_books' %}"> <i style="margin-right: 5px; "class="fas fa-heart"></i>Wish List</a>
			</li>
			{% endif %}
			
		</ul>
		<!--
	
		<i class="fas fa-sign-out-alt"></i>
		<i class="fas fa-sign-in-alt"></i>
		-->
	</div>
</div>