store/blog/urls.py
from django.urls import path
from . import views


app_name='blog'



urlpatterns = [
    path('', views.blogView, name='blog_list'),
    path('<int:id>/detail/', views.blogDetail, name='blog_detail'),
    path('add-blog/', views.addBlog, name="add_blog")
]

store/bookstore_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('contact/', include('contact.urls')),
    path('order/',include('order.urls')),
    path('blog/', include('blog.urls')),
    path('vouchers/',include('vouchers.urls',namespace='vouchers')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('add/<slug:book_slug>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<slug:book_slug>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<slug:book_slug>/', views.full_remove, name='full_remove'),
]

store/order/urls.py
from django.urls import path
from . import views
from .views import RequestRefundView

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', views.orderHistory, name='order_history'),
    path('<int:order_id>/', views.viewOrder, name='order_detail'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

store/shop/urls.py
from django.urls import path
from . import views


app_name='shop'


urlpatterns = [
    path('', views.allBookCat, name='allBookCat'),
    path('books/<slug:category_slug>/', views.allBookCat, name='books_by_category'),
    path('books/<slug:category_slug>/<slug:book_slug>/', views.book_detail, name='book_detail'),
    path('new/', views.managerCreateView, name='book_new'),
    path('booksManagerList/', views.bookListView, name='book_list'),
    path('books/<slug:category_slug>/<slug:book_slug>/edit/', views.bookUpdateView, name='book_edit'),
    path('books/<slug:category_slug>/<slug:book_slug>/delete/',views.bookDeleteView, name='book_delete'),
    path('books/<slug:category_slug>/<slug:book_slug>/add', views.add_to_wishList, name='add_wishlist'),
    path('wishlists/',views.viewWishList, name='wishList_books'),
    path('books/<slug:book_slug>/delete', views.delete_from_wishList, name='wishList_delete'),
    path('top_rated/', views.topRatedBooks, name='topRatedBooks'),
    path('best_value/', views.cheapBooks, name='cheapBooks'),
    path('books/<slug:category_slug>/<slug:book_slug>/add_review/', views.addReview, name="add_review"),
    path('reviews/',views.reviewList, name="reviewList"),

    

]

store/shop/models.py
from django.db import models
import uuid
from django.urls import reverse
from django.conf import settings
from autoslug import AutoSlugField
from django.core.validators import MinValueValidator,  MaxValueValidator


class Category(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default = uuid.uuid4,
        editable = False)

    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)
    popularity = models.PositiveSmallIntegerField()
    slug = AutoSlugField(null=True, default=None, unique=True, populate_from='name')
    '''books = models.ManyToManyField('Book')'''

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:books_by_category', args=[self.slug])

    def __str__(self):
        return self.name
 
class Author(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable =False)
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    full_name = models.CharField(max_length=250,default='SOME STRING')
    age = models.PositiveSmallIntegerField()
    about = models.TextField(blank=True)

    

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

class Book(models.Model):
        id = models.UUIDField(
            primary_key=True,
            default=uuid.uuid4,
            editable=False)
        iban = models.CharField(unique=True, max_length=250)
        title = models.CharField(max_length=250, unique=True)
        synopsis = models.TextField(blank=True)
        price = models.DecimalField(max_digits=10, decimal_places=2)
        star_rating = models.FloatField()
        image = models.ImageField(upload_to='books', blank=True)
        stock = models.IntegerField()
        availible = models.BooleanField(default=True)
        created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
        updated = models.DateTimeField(auto_now=True, blank=True, null=True)
        pub_date = models.DateField(blank=True, null=True)
        num_pages = models.IntegerField()
        publisher = models.CharField(max_length=240)
        author = models.ForeignKey(Author, related_name='authors', on_delete=models.CASCADE)
        category = models.ForeignKey(Category, on_delete=models.CASCADE,null=False)
        slug = AutoSlugField(null=True, default=None, unique=True, populate_from='title')

        class Meta:
            ordering = ('title', )
            verbose_name = 'book'
            verbose_name_plural = 'books'
        
        def get_absolute_url(self):
            return reverse('shop:book_detail',args=[self.category.slug, self.slug])

        def temp_url(self):
            return self.category.slug, self.slug
        
        def __str__(self):
            return self.title



class WishList(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    wished_item = models.ForeignKey(Book, on_delete=models.CASCADE)
    added_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.wished_item.title

    def get_absolute_url(self):
            return reverse('shop:wishList_books')


class Review(models.Model):
    name = models.CharField(max_length=50)
    subject = models.CharField(max_length=40)
    comment = models.CharField(max_length=240)
    review_item = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.IntegerField(default="1", validators=[MinValueValidator(1), MaxValueValidator(5)] )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.subject

    def get_absolute_url(self):
            return reverse('shop:book_detail',args=[self.review_item.category.slug, self.review_item.slug])



    

    

            

store/shop/forms.py
from django.forms import ModelForm
from .models import Book, Category,Review


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

class BookRatingForm(ModelForm):
    class Meta:
        model = Book
        fields = ['star_rating']


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['subject','rating', 'comment']

store/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Book, WishList, Review
from django.urls import reverse_lazy
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from .forms import BookForm, ReviewForm, BookRatingForm
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView, DetailView
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.urls import reverse
from django.contrib import messages
from order.models import Order
from accounts.models import CustomUser, UserProfile
from django.core.exceptions import ValidationError
from vouchers.models import Voucher


def group_check(user):
    if user.groups.filter(name="Manager").exists() == True:
        return True
    else:
        return False

@login_required()
def reviewList(request):
    reviews = Review.objects.filter(user = request.user)
   
    return render(request, 'shop/reviews.html', {'reviews':reviews})
    

def cheapBooks(request):
    booksCheapF = Book.objects.filter(category='b6e303f8-d681-4aa2-ab8a-ad3b27a62015')
    booksCheapFiction = booksCheapF.order_by('price')[:6]

    booksCheapC= Book.objects.filter(category='1a8c0bf6-85cf-4170-ab6b-45604dd43cf2')
    booksCheapChildren = booksCheapC.order_by('price')[:6]

    booksCheapN= Book.objects.filter(category='f1b46f0d-7ee6-4ecb-a649-aaeb6407f836')
    booksCheapNon = booksCheapN.order_by('price')[:6]

    for i in booksCheapChildren:
        print(i.price)

    for l in booksCheapFiction:
        print(l.price)
    
    for j in booksCheapNon:
        print(j.price)



    return render(request, 'shop/book_cheap.html', {'booksCheapChildren':booksCheapChildren, 'booksCheapFiction':booksCheapFiction,'booksCheapNon':booksCheapNon })


def topRatedBooks(request):

    

    booksPopulateF = Book.objects.filter(category='b6e303f8-d681-4aa2-ab8a-ad3b27a62015')
    booksRatedFiction = booksPopulateF.order_by('-star_rating')[:6]

    booksPopC= Book.objects.filter(category='1a8c0bf6-85cf-4170-ab6b-45604dd43cf2')
    booksRatedChildren = booksPopC.order_by('-star_rating')[:6]

    booksPopN= Book.objects.filter(category='f1b46f0d-7ee6-4ecb-a649-aaeb6407f836')
    booksRatedNon = booksPopN.order_by('-star_rating')[:6]

    for i in booksRatedChildren:
        print(i.star_rating)

    for l in booksRatedFiction:
        print(l.star_rating)
    
    for j in booksRatedNon:
        print(j.star_rating)



    return render(request, 'shop/book_rating.html', {'booksRatedChildren':booksRatedChildren, 'booksRatedFiction':booksRatedFiction,'booksRatedNon':booksRatedNon })

def book_detail(request, category_slug, book_slug):
  
    bookCategory = Book.objects.filter(category__slug =category_slug)
    booksInCategory = bookCategory.order_by('?')[:6]

    print(request.POST)
    form = ReviewForm()
    try:
        book = Book.objects.get(category__slug=category_slug, slug=book_slug)
    except Exception as e:
        raise e

    Booker = Book.objects.all()


    rating_form = BookRatingForm()
    ratings = Review.objects.filter(review_item__slug = book_slug)
    one = 0
    two = 0
    three = 0
    four = 0
    five = 0
    half = False
    for i in ratings:
        if i.rating == 1:
            one = one +1
        if i.rating == 2:
            two = two +1
        if i.rating == 3:
            three = three +1
        if i.rating == 4:
            four = four +1
        if i.rating == 5:
            five = five +1
    try:
        total = (5*five + 4*four + 3*three + 2*two +1*one) / (one +two+three+four+five)
    except ZeroDivisionError as e:
        total = 0

    book.star_rating = total
    book.save()
        
    rounded = round(total)
    print(total)
    print(rounded)
    if total >= 1.5 and total < 2:
        rounded = 1
        half = True
    if total >= 2.5 and total < 3:
        rounded = 2
        half = True
    if total >= 3.5 and total < 4:
        rounded = 3
        half = True
    if total >= 4.5 and total < 5:
        rounded = 4
        half = True
    if total >= 5.0:
        rounded = 5
        half = False
        print("hello")
    
    print(rounded)
    UserImage = UserProfile.objects.all()
    reviewss = Review.objects.filter(review_item__slug=book_slug)
    reviews = reviewss.order_by('-created_date')

    

    
    if half:
        greyStars = 4 - rounded
    else:
        greyStars = 5 - rounded

    print(greyStars)
    print(rounded)

    

    return render(request, 'shop/book.html', {'booksInCategory':booksInCategory, 'book':book,'UserImage':UserImage, 'half':half, 'form':form, 'reviews':reviews, 'rounded':rounded, 'greyStars':greyStars})

@login_required()
def add_to_wishList(request, book_slug, category_slug):
    print(book_slug)
    book = get_object_or_404(Book, slug=book_slug)
    

    try :
        obj = WishList.objects.get(user=request.user, wished_item=book)
        messages.warning(request, 'Item already added in wishlist ')
        
    except WishList.DoesNotExist:
        obj = WishList.objects.create(
            user = request.user, 
            wished_item=book,
        )
        obj.save()
        messages.success(request,'"' +str(obj.wished_item) +'" added to Wish List')
   
    return HttpResponseRedirect(book.get_absolute_url())

@login_required()
def delete_from_wishList(request, book_slug):
    
    book = WishList.objects.get(wished_item__slug=book_slug, user = request.user)
    book.delete()
    messages.success(request, 'Successfully deleted from Wish List')

    return HttpResponseRedirect('/wishlists/')


@login_required() 
def viewWishList(request):
    managerCheck = False
    books = WishList.objects.filter(user = request.user)
    return render(request, 'shop/wishlist_books.html', {'books':books})

def allBookCat(request, category_slug=None):
    managerCheck = False

  

    if request.user.groups.filter(name="Manager").exists() == True:
        managerCheck = True

    c_page = None
    books = None
    if category_slug != None:
        c_page = get_object_or_404(Category, slug=category_slug)
        books = Book.objects.filter(category=c_page, availible=True) 
    else:
        books = Book.objects.all().filter(availible=True)
    
    paginator = Paginator(books,24)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        books = paginator.page(page)
    except (EmptyPage,InvalidPage):
        books = paginator.page(paginator.num_pages) 

    return render(request, 'shop/category.html', {'category':c_page,'books':books,'managerCheck':managerCheck })

@user_passes_test(group_check)
def managerCreateView(request):

    vouchers_count = Voucher.objects.count()
    managerCheck = True
    books = Book.objects.all()
    books_count = Book.objects.count()
    orders_count = Order.objects.count()
    users_count = CustomUser.objects.count() 
    books = Book.objects.all().filter(availible=True)
    managerCheck = True
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('')

    else:
        form = BookForm()

    return render(request, 'shop/book_new.html', {'form':form,'managerCheck':managerCheck,
            'books_count' : books_count,
        'orders_count' : orders_count,
        'users_count' : users_count,
        'books':books,
        'managerCheck':managerCheck,
        "vouchers_count":vouchers_count
    
    })

@user_passes_test(group_check)
def bookListView(request):
    vouchers_count = Voucher.objects.count()
    managerCheck = True
    books = Book.objects.all()
    books_count = Book.objects.count()
    orders_count = Order.objects.count()
    users_count = CustomUser.objects.count() 
    context = {
        'books_count' : books_count,
        'orders_count' : orders_count,
        'users_count' : users_count,
        'books':books,
        'managerCheck':managerCheck,
        "vouchers_count":vouchers_count
        }
    return render(request, 'shop/book_list.html', context)

@user_passes_test(group_check)
def bookUpdateView(request, category_slug, book_slug):
    managerCheck = True
    managerCheck = True
    vouchers_count = Voucher.objects.count()
    orders = Order.objects.all()
    books = Book.objects.all()
    books_count = books.count()
    orders_count = orders.count()
    users_count = CustomUser.objects.count()
    book = Book.objects.get(category__slug=category_slug, slug=book_slug)

    form = BookForm(request.POST or None, request.FILES or None , instance = book)
    if form.is_valid():
        print(request.POST)
        form.save()
        return HttpResponseRedirect('/')

    return render(request, 'shop/book_edit.html', {'form':form,'managerCheck':managerCheck,
    "orders" : orders,
        "books" : books,
        "books_count" : books_count,
        "orders_count" : orders_count,
        "users_count" : users_count,
        "vouchers_count":vouchers_count
    
    })

@user_passes_test(group_check)
def bookDeleteView(request, category_slug, book_slug):
    vouchers_count = Voucher.objects.count()
    managerCheck = True
    orders = Order.objects.all()
    books = Book.objects.all()
    books_count = books.count()
    orders_count = orders.count()
    users_count = CustomUser.objects.count()
    book = Book.objects.get(category__slug=category_slug, slug=book_slug)
    
    if request.method =="POST":
        book.delete()
        return HttpResponseRedirect('/')

    return render(request, 'shop/book_delete.html', {'book':book,'managerCheck':managerCheck,
    "orders" : orders,
        "books" : books,
        "books_count" : books_count,
        "orders_count" : orders_count,
        "users_count" : users_count,
         "vouchers_count":vouchers_count
    

store/shop/templates/shop/book_list.html
{% block content %}
{% include "dashboard/manager_navigation.html" %}
<div class="container">
<div class="row py-5">
<div class="col-md-4">
<a style="font-size: 20px;" class="btn btn-lg btn-info" href="{% url 'shop:book_new' %}">Add Book +</a>
</div>
<div class="col-md-8">
<h1 class="py-5">Inventory</h1>
<table class="table">
<thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Category</th>
      <th scope="col">Quantity</th>
	  <th scope="col">Activity</th>
    </tr>
  </thead>
    <tbody>
{% for book in books %}
<tr>
<th scope="row"><a href="{{book.get_absolute_url}}"><img class="float-left img-thumbnail" style="width:100px; height:auto;" src="{{book.image.url}}" alt="{{book.title}}"></a></th>
<td>{{ book.title }}</td>
<td>{{ book.category.slug }}</td>
<td>{{ book.stock }}</td></a>
<td><a style="font-size: 15px;" class="btn btn-info btn-sm my-2" href="{% url 'shop:book_edit' book.category.slug book.slug %}">Edit</a><a style="font-size: 15px;" class="btn btn-danger btn-sm my-2" href="{% url 'shop:book_delete' book.category.slug book.slug %}">Delete</a></td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
</div>
</div>

{% endblock content%}

store/shop/templates/shop/category.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
	{% if category %}
		{{ category.description|truncatewords:155 }}
	{% else %}
		Welcome to the Online Book Store where you can buy awesome books.
	{% endif %}
{% endblock %}
{% block title %}
	{% if category %}
		{{ category.name }} - Online Book Store
	{% else %}
		Bookspace.
	{% endif %}
{% endblock %}
{% block content %}



{% if managerCheck %}


	
{% endif %}
	<!--Breadcrumb navigation-->
	{% if category %}
		<div class="row my_row_class">
			<div class="mx-auto">
				<p><a style="font-weight: bolder; font-family: 'Baskervville', serif; font-size: 20px;" href="{% url 'shop:allBookCat' %}">Our book Collection</a> | {{category.name}}</p>
			</div>
        </div>
    {% endif %}
	<div style=" overflow-x: hidden; margin-top: -10px;;" class="mx-auto">
	{% if category.image %}
	<a href="{% url 'shop:allBookCat' %}">
		<img style="width:100vw" class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
	</a>
	</div>
	
	<br>
	<div>
		<h1 class="text-center my_title" >{{category.name}}</h1>
		<p class="text-justify">{{category.description}}</p>
    </div>
   {% else %}

   <a href="{% url 'shop:allBookCat' %}">
		<img style="width:100vw;" class="my_image my_image_padding " src="{% static 'images/banner2.jpeg' %}" alt="Our Book Collection">
	</a>
	</div>
	<br>
	<div>
		<h1 style=" font-family: 'Baskervville', serif; margin-bottom: -50px;"class=" text-center my_title" >Our Book Collection</h1>
		<p class="text-justify"></p>
	
	</div>
    {% endif %}

	<style>
.imHover{
				transition: 100.1ms ease-in;
			}
			.imHover:hover{

				background-color: #282d32;
				color: white;
				transform: translateY(-9px);
			}
	</style>
   <div class="container-fluid">
		<div style=" margin: 100px 200px;" class="row"> 
			{% for book in books %}
		
				<div class="mb-5 col-9 col-lg-2 col-sm-3 col-md-4">
					<div style="font-size: 10px; " class="card text-center h-150 text-sm border-0" style="min-width: 1rem; ">
						
						<a href="{{book.get_absolute_url}}"><img  data-toggle="tooltip" title="{{book.title}}" class="card-img-top my_image imHover" style="width: 150px;;" src="{{book.image.url}}" alt="{{book.title}}">
							</a>
						<div  class="card-body">
							<h3 style="font-weight: bolder; font-family: 'Baskervville', serif; font-size: 14px;" class="card-text" >{{book.title}}</h3>
							<p class="card-text">€{{book.price}}</p>
							<p style="color: rgb(114, 91, 69);" class="card-text">{{book.author}}</p>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
		<script>
			images = document.querySelector(".imHover")
			text = document.querySelector(".hoverer")

			images.addEventListener("",myFunction )

			function myFunction(){

				images.appendChild(text)
				
			}
		</script>
		<div class="mx-auto" style="margin-top: 30px; margin-bottom: 130px;">
			{% if books.paginator.num_pages > 1 %}
				<hr>
				<div class="text-center">
					{% for pg in books.paginator.page_range %}
						<a href="?page={{pg}}" class="btn btn-light btn-sm
							{% if books.number == pg %}active{% endif %}">{{pg}}
						</a>
					{% endfor %}
				</div>
			{% endif %}
		
	</div>		
	</div>

		


{% endblock %}

store/shop/templates/shop/reviews.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<style>
	.menu {
		height: 30vh;
		width: 200px;
		z-index: 1;
		left: 0;
		margin-top: 55px;


		padding-top: 20px;
		background-color: #282d32;
		position: absolute;
		margin-bottom: -40px;

		

	}
	.menu a {
		text-decoration: none;
		list-style-type: none;
		display: block;
		text-transform: uppercase;
	}

	.menu a:hover {
		background-color: grey;
	}
</style>
<div class="container">

    <div class="menu">

		<a style=" font-weight:20px; " href="{% url 'dashboard_view'%}" class="text-justify text-light btn rounded-0">
			<i class="fas fa-chevron-left"></i>dashboard
		</a>
		<a style=" font-weight:20px" href="{% url 'profile_view'%}" class="text-justify text-light btn  rounded-0">Profile </a>
		<a style=" font-weight:20px" href="{% url 'shop:wishList_books'%}"
			class="text-justify text-light btn rounded-0 ">Wishlist</a>
		<a style=" font-weight:20px" href="{% url 'order:order_history'%}"
			class="text-justify text-light btn rounded-0">Orders</a>
		<a href="{% url 'shop:reviewList'%}" style="  font-weight:20px" class="text-justify disabled text-light btn rounded-0"
			aria-disabled="true">Reviews</a>


	</div>




   
	<br>
	<h1  class="text-justify my_title ml-5 pl-5">Reviews</h1>
	<br>
	
<div class="row">
	<div class="col-1">

	</div>
	<div class="col-11">

	<div class="row">

	
    
    {% if reviews %}

        {% for review in reviews%}

        <div class="col-3 reviewCard border-bottom">


            <div class="card border-0">
                <div style=" font-size: 20px; font-style: italic; font-family: Arial, Helvetica, sans-serif; background-color: white;"class="card-header border-0">
					<img style="width: 200px;" src="{{review.review_item.image.url}}">
					"{{review.subject}}"
                </div>
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <p style="font-size: 15px; font-weight: lighter;">{{review.comment}}</p>
                        <footer class="">
                            <p style="text-transform: uppercase; font-size: 12px; font-weight: bolder;">{{review.name}}</p>
                            <p style="text-transform: uppercase; font-size: 12px; margin-top: -17px; ">{{review.created_date}}</p>
                        </footer>
                        <blockquote>
                </div>
            </div>

        </div>
   

        {%endfor%}
	</div>
</div>
    </div>
 
{%else%}
<h1 class="text-center my-5 py-5">No Reviews by {{request.user}}</h1>

{%endif%}

</div>


</div>

{%endblock content%}

store/shop/templates/shop/wishlist_books.html
{% extends 'base.html'%}
{% block content %}

<style>
	.menu {
		height: 30vh;
		width: 200px;
		z-index: 1;
		left: 0;
		margin-top: 55px;


		padding-top: 20px;
		background-color: #282d32;
		position: absolute;
		margin-bottom: -40px;

		

	}

	.menu a {
		text-decoration: none;
		list-style-type: none;
		display: block;
		text-transform: uppercase;
	}

	.menu a:hover {
		background-color: grey;
	}
</style>
    <div  class="container-fluid pt-1">

        <div class="menu">

            <a style=" font-weight:20px; " href="{% url 'dashboard_view'%}" class="text-justify text-light btn rounded-0">
                <i class="fas fa-chevron-left"></i> dashboard
            </a>
            <a style=" font-weight:20px" href="{% url 'profile_view'%}" class="text-justify text-light btn  rounded-0">Profile </a>
            <a style=" font-weight:20px" href="{% url 'shop:wishList_books'%}"
                class="text-justify text-light btn rounded-0 disabled">Wishlist</a>
            <a style=" font-weight:20px" href="{% url 'order:order_history'%}"
                class="text-justify text-light btn rounded-0">Orders</a>
            <a href="{% url 'shop:reviewList'%}" style="  font-weight:20px" class="text-justify  text-light btn rounded-0"
                aria-disabled="true">Reviews</a>
    
    
        </div>

        <div class="row">
            <div class="col-2">

            </div>
            
        
        <div class="col-10">
            <br>
            <h1 class="text-justify my_title">Wish List</h1>
            <br>
        {% if books %}
        <div class="row " style="margin: 0 ;"> 
            {% for book in books %}
        
                <div class="my_bottom_margin col-2">
                    <div style="font-size: 10px; " class="card text-center h-50 border-0" style="min-width: 18rem;">
                        <a href="{{book.wished_item.get_absolute_url}}"><img style="width: 150px;;" class="card-img-top my_image" src="{{book.wished_item.image.url}}" alt="{{book.title}}"></a>
                        <div class="card-body">
                            <h4 class="card-text" >{{book.wished_item.title}}</h4>
                            <p class="card-text">€{{book.wished_item.price}}</p>
                            <p style="color: rgb(114, 91, 69);" class="card-text">{{book.wished_item.author}}</p>
                            <a style="font-size: 10px;"class="btn btn-danger" href="{% url 'shop:wishList_delete' book.wished_item.slug %}">Delete</a>
                            <br>
                            <a  style="font-size: 10px;"class="btn btn-secondary mt-2" href="{% url 'cart:add_cart' book.wished_item.slug %}">Add to Cart</a>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
        {% else %}
        <p class="card-text text-center mt-3">No books in wishlist</p>
        {% endif %}
        </div>
</div>
</div>
 
{% endblock content%}